---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kristanwebb/zamia.co.uk/subdomains/ts/
    - /bin/echo $DEPLOYPATH
    - /bin/echo --------
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R web $DEPLOYPATH
    - /bin/cp composer.* $DEPLOYPATH
